//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Windows.Forms.Resources {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SystemResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SystemResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Windows.Forms.GTKSystem.Resources.Extensions.SystemResources", typeof(SystemResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ResourceReader class does not know how to read this version of .resources files. Expected version: {0}  This file: {1}.
        /// </summary>
        internal static string Arg_ResourceFileUnsupportedVersion {
            get {
                return ResourceManager.GetString("Arg_ResourceFileUnsupportedVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream was not readable.
        /// </summary>
        internal static string Argument_StreamNotReadable {
            get {
                return ResourceManager.GetString("Argument_StreamNotReadable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream was not writable..
        /// </summary>
        internal static string Argument_StreamNotWritable {
            get {
                return ResourceManager.GetString("Argument_StreamNotWritable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream length must be non-negative and less than 2^31 - 1 - origin..
        /// </summary>
        internal static string ArgumentOutOfRange_StreamLength {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_StreamLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrupt .resources file.  The specified type doesn&apos;t exist..
        /// </summary>
        internal static string BadImageFormat_InvalidType {
            get {
                return ResourceManager.GetString("BadImageFormat_InvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrupt .resources file. String length must be non-negative..
        /// </summary>
        internal static string BadImageFormat_NegativeStringLength {
            get {
                return ResourceManager.GetString("BadImageFormat_NegativeStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrupt .resources file.  The specified data length &apos;{0}&apos; is not a valid position in the stream..
        /// </summary>
        internal static string BadImageFormat_ResourceDataLengthInvalid {
            get {
                return ResourceManager.GetString("BadImageFormat_ResourceDataLengthInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrupt .resources file. A resource name extends past the end of the stream..
        /// </summary>
        internal static string BadImageFormat_ResourceNameCorrupted {
            get {
                return ResourceManager.GetString("BadImageFormat_ResourceNameCorrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrupt .resources file. The resource name for name index {0} extends past the end of the stream..
        /// </summary>
        internal static string BadImageFormat_ResourceNameCorrupted_NameIndex {
            get {
                return ResourceManager.GetString("BadImageFormat_ResourceNameCorrupted_NameIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrupt .resources file. Invalid offset &apos;{0}&apos; into data section..
        /// </summary>
        internal static string BadImageFormat_ResourcesDataInvalidOffset {
            get {
                return ResourceManager.GetString("BadImageFormat_ResourcesDataInvalidOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrupt .resources file. Unable to read resources from this file because of invalid header information. Try regenerating the .resources file..
        /// </summary>
        internal static string BadImageFormat_ResourcesHeaderCorrupted {
            get {
                return ResourceManager.GetString("BadImageFormat_ResourcesHeaderCorrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrupt .resources file. String for name index &apos;{0}&apos; extends past the end of the file..
        /// </summary>
        internal static string BadImageFormat_ResourcesIndexTooLong {
            get {
                return ResourceManager.GetString("BadImageFormat_ResourcesIndexTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrupt .resources file. Invalid offset &apos;{0}&apos; into name section..
        /// </summary>
        internal static string BadImageFormat_ResourcesNameInvalidOffset {
            get {
                return ResourceManager.GetString("BadImageFormat_ResourcesNameInvalidOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrupt .resources file. Resource name extends past the end of the file..
        /// </summary>
        internal static string BadImageFormat_ResourcesNameTooLong {
            get {
                return ResourceManager.GetString("BadImageFormat_ResourcesNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type serialized in the .resources file was not the same type that the .resources file said it contained. Expected &apos;{0}&apos; but read &apos;{1}&apos;..
        /// </summary>
        internal static string BadImageFormat_ResType_SerBlobMismatch {
            get {
                return ResourceManager.GetString("BadImageFormat_ResType_SerBlobMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrupt .resources file.  The specified type doesn&apos;t match the available data in the stream..
        /// </summary>
        internal static string BadImageFormat_TypeMismatch {
            get {
                return ResourceManager.GetString("BadImageFormat_TypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many bytes in what should have been a 7 bit encoded Int32..
        /// </summary>
        internal static string Format_Bad7BitInt32 {
            get {
                return ResourceManager.GetString("Format_Bad7BitInt32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumeration already finished..
        /// </summary>
        internal static string InvalidOperation_EnumEnded {
            get {
                return ResourceManager.GetString("InvalidOperation_EnumEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumeration has not started. Call MoveNext..
        /// </summary>
        internal static string InvalidOperation_EnumNotStarted {
            get {
                return ResourceManager.GetString("InvalidOperation_EnumNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource was of type &apos;{0}&apos; instead of String - call GetObject instead..
        /// </summary>
        internal static string InvalidOperation_ResourceNotString_Type {
            get {
                return ResourceManager.GetString("InvalidOperation_ResourceNotString_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resource writer has already been closed and cannot be edited..
        /// </summary>
        internal static string InvalidOperation_ResourceWriterSaved {
            get {
                return ResourceManager.GetString("InvalidOperation_ResourceWriterSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This platform does not support binary serialized resources..
        /// </summary>
        internal static string NotSupported_BinarySerializedResources {
            get {
                return ResourceManager.GetString("NotSupported_BinarySerializedResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot read resources that depend on serialization..
        /// </summary>
        internal static string NotSupported_ResourceObjectSerialization {
            get {
                return ResourceManager.GetString("NotSupported_ResourceObjectSerialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream does not support seeking..
        /// </summary>
        internal static string NotSupported_UnseekableStream {
            get {
                return ResourceManager.GetString("NotSupported_UnseekableStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This .resources file should not be read with this reader. The resource reader type is &quot;{0}&quot;..
        /// </summary>
        internal static string NotSupported_WrongResourceReader_Type {
            get {
                return ResourceManager.GetString("NotSupported_WrongResourceReader_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot access a closed resource set..
        /// </summary>
        internal static string ObjectDisposed_ResourceSet {
            get {
                return ResourceManager.GetString("ObjectDisposed_ResourceSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResourceReader is closed..
        /// </summary>
        internal static string ResourceReaderIsClosed {
            get {
                return ResourceManager.GetString("ResourceReaderIsClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream is not a valid resource file..
        /// </summary>
        internal static string Resources_StreamNotValid {
            get {
                return ResourceManager.GetString("Resources_StreamNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load a converter for type {0}..
        /// </summary>
        internal static string TypeLoadException_CannotLoadConverter {
            get {
                return ResourceManager.GetString("TypeLoadException_CannotLoadConverter", resourceCulture);
            }
        }
    }
}
