//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTKSystemWinFormsApp11.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GTKSystemWinFormsApp11.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DropdownList 1.
        /// </summary>
        public static string GtkForm_GtkForm_dropdown_list_1 {
            get {
                return ResourceManager.GetString("GtkForm_GtkForm_dropdown list 1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DropDownMenu.
        /// </summary>
        public static string GtkForm_InitializeComponent_DropSownMenu {
            get {
                return ResourceManager.GetString("GtkForm_InitializeComponent_DropSownMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string GtkForm_InitializeComponent_Item {
            get {
                return ResourceManager.GetString("GtkForm_InitializeComponent_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string GtkForm_InitializeComponent_Menu {
            get {
                return ResourceManager.GetString("GtkForm_InitializeComponent_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open main window.
        /// </summary>
        public static string GtkForm_InitializeComponent_Open_main_window {
            get {
                return ResourceManager.GetString("GtkForm_InitializeComponent_Open_main_window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Text.
        /// </summary>
        public static string GtkForm_InitializeComponent_Open_Status_Text {
            get {
                return ResourceManager.GetString("GtkForm_InitializeComponent_Open_Status_Text", resourceCulture);
            }
        }
    }
}
