//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gtk.Windows.Forms.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gtk.Windows.Forms.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* css file path */.
        /// </summary>
        internal static string Application_Init_css_file_path {
            get {
                return ResourceManager.GetString("Application_Init_css file path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* Custom theme name */.
        /// </summary>
        internal static string Application_Init_Custom_theme_name {
            get {
                return ResourceManager.GetString("Application_Init_Custom theme name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define control style.
        /// </summary>
        internal static string Application_Init_Define_control_style {
            get {
                return ResourceManager.GetString("Application_Init_Define control style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =》Directory does not exist.
        /// </summary>
        internal static string Application_Init_Directory_does_not_exist {
            get {
                return ResourceManager.GetString("Application_Init_Directory_does_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* Freely defined style files */.
        /// </summary>
        internal static string Application_Init_Freely_defined_style_files {
            get {
                return ResourceManager.GetString("Application_Init_Freely defined style files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* Here you can customize or adjust the control style */ .
        /// </summary>
        internal static string Application_Init_Here_you_can_customize_or_adjust_the_control_style {
            get {
                return ResourceManager.GetString("Application_Init_Here you can customize or adjust the control style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*Specify the theme, valid when AutoTheme=false*/.
        /// </summary>
        internal static string Application_Init_Specify_the_theme__valid_when_AutoTheme_is_false {
            get {
                return ResourceManager.GetString("Application_Init_Specify the theme, valid when AutoTheme is false", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* The folder where the theme files are located */.
        /// </summary>
        internal static string Application_Init_The_folder_where_the_theme_files_are_located {
            get {
                return ResourceManager.GetString("Application_Init_The folder where the theme files are located", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*Whether to apply built-in styles*/.
        /// </summary>
        internal static string Application_Init_Whether_to_apply_built_in_styles {
            get {
                return ResourceManager.GetString("Application_Init_Whether to apply built-in styles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*Whether to follow the system theme by default*/.
        /// </summary>
        internal static string Application_Init_Whether_to_follow_the_system_theme_by_default {
            get {
                return ResourceManager.GetString("Application_Init_Whether to follow the system theme by default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*Whether to use a custom theme, corresponding to [custom theme]*/.
        /// </summary>
        internal static string Application_Init_Whether_to_use_a_custom_theme__corresponding_to_custom_theme {
            get {
                return ResourceManager.GetString("Application_Init_Whether to use a custom theme, corresponding to custom theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*Whether to use custom style, corresponding to [custom style]*/.
        /// </summary>
        internal static string Application_Init_Whether_to_use_custom_style__corresponding_to__custom_style_ {
            get {
                return ResourceManager.GetString("Application_Init_Whether to use custom style, corresponding to [custom style]", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose color.
        /// </summary>
        internal static string ColorDialog_RunDialog_Choose_color {
            get {
                return ResourceManager.GetString("ColorDialog_RunDialog_Choose color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DateTimePicker {
            get {
                object obj = ResourceManager.GetObject("DateTimePicker", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected date is outside the restricted range \nMaximum time: {0}\nMinimum time: {1}.
        /// </summary>
        internal static string DateTimePicker_Calendar_DaySelected_Choose {
            get {
                return ResourceManager.GetString("DateTimePicker_Calendar_DaySelected_Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date restrictions.
        /// </summary>
        internal static string DateTimePicker_Calendar_DaySelected_Date_restrictions {
            get {
                return ResourceManager.GetString("DateTimePicker_Calendar_DaySelected_Date restrictions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Today .
        /// </summary>
        internal static string DateTimePicker_DateTimePicker_Choose_Today {
            get {
                return ResourceManager.GetString("DateTimePicker_DateTimePicker_Choose Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ____year__month__day.
        /// </summary>
        internal static string DateTimePicker_DateTimePicker_Mask {
            get {
                return ResourceManager.GetString("DateTimePicker_DateTimePicker_Mask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MM month dd day yyyy year.
        /// </summary>
        internal static string DateTimePicker_Value_yyyy年MM月dd日 {
            get {
                return ResourceManager.GetString("DateTimePicker_Value_yyyy年MM月dd日", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select file.
        /// </summary>
        internal static string FileDialog_RunDialog_Select_file {
            get {
                return ResourceManager.GetString("FileDialog_RunDialog_Select file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select font.
        /// </summary>
        internal static string FontDialog_RunDialog_Select_font {
            get {
                return ResourceManager.GetString("FontDialog_RunDialog_Select font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are closing this window, are you sure you want to close it?.
        /// </summary>
        internal static string FormBase_FormBase_Close_ {
            get {
                return ResourceManager.GetString("FormBase_FormBase_Close_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string MessageBox_ShowCore_Cancel {
            get {
                return ResourceManager.GetString("MessageBox_ShowCore_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string MessageBox_ShowCore_Close {
            get {
                return ResourceManager.GetString("MessageBox_ShowCore_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string MessageBox_ShowCore_Help {
            get {
                return ResourceManager.GetString("MessageBox_ShowCore_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string MessageBox_ShowCore_No {
            get {
                return ResourceManager.GetString("MessageBox_ShowCore_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string MessageBox_ShowCore_OK {
            get {
                return ResourceManager.GetString("MessageBox_ShowCore_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        internal static string MessageBox_ShowCore_Reject {
            get {
                return ResourceManager.GetString("MessageBox_ShowCore_Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string MessageBox_ShowCore_Yes {
            get {
                return ResourceManager.GetString("MessageBox_ShowCore_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is in use and cannot be overwritten.
        /// </summary>
        internal static string PrintDialog_RunPrint_File_is_in_use_and_cannot_be_overwritten {
            get {
                return ResourceManager.GetString("PrintDialog_RunPrint_File is in use and cannot be overwritten", resourceCulture);
            }
        }
    }
}
