//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTKWinFormsApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GTKWinFormsApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Open File.
        /// </summary>
        public static string CommonDialogsForm_button3_Click_Test_Open_File {
            get {
                return ResourceManager.GetString("CommonDialogsForm_button3_Click_Test_Open_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Save File.
        /// </summary>
        public static string CommonDialogsForm_button6_Click_Test_Save_File {
            get {
                return ResourceManager.GetString("CommonDialogsForm_button6_Click_Test_Save_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse Folder Description.
        /// </summary>
        public static string CommonDialogsForm_button7_Click_Browse_Folder_Description {
            get {
                return ResourceManager.GetString("CommonDialogsForm_button7_Click_Browse_Folder_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doubt.
        /// </summary>
        public static string CommonDialogsForm_button9_Click_Doubt {
            get {
                return ResourceManager.GetString("CommonDialogsForm_button9_Click_Doubt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warn.
        /// </summary>
        public static string CommonDialogsForm_button9_Click_Warn {
            get {
                return ResourceManager.GetString("CommonDialogsForm_button9_Click_Warn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Button 1.
        /// </summary>
        public static string CommonDialogsForm_CommonDialogsForm_0 {
            get {
                return ResourceManager.GetString("CommonDialogsForm_CommonDialogsForm_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning Message.
        /// </summary>
        public static string CommonDialogsForm_CommonDialogsForm_1 {
            get {
                return ResourceManager.GetString("CommonDialogsForm_CommonDialogsForm_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse Folder.
        /// </summary>
        public static string CommonDialogsForm_CommonDialogsForm_3 {
            get {
                return ResourceManager.GetString("CommonDialogsForm_CommonDialogsForm_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save File.
        /// </summary>
        public static string CommonDialogsForm_CommonDialogsForm_4 {
            get {
                return ResourceManager.GetString("CommonDialogsForm_CommonDialogsForm_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open File.
        /// </summary>
        public static string CommonDialogsForm_CommonDialogsForm_5 {
            get {
                return ResourceManager.GetString("CommonDialogsForm_CommonDialogsForm_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banner Bar.
        /// </summary>
        public static string CommonDialogsForm_CommonDialogsForm_6 {
            get {
                return ResourceManager.GetString("CommonDialogsForm_CommonDialogsForm_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node 3.
        /// </summary>
        public static string CommonDialogsForm_CommonDialogsForm_Node_1 {
            get {
                return ResourceManager.GetString("CommonDialogsForm_CommonDialogsForm_Node_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node 2.
        /// </summary>
        public static string CommonDialogsForm_CommonDialogsForm_Node_2 {
            get {
                return ResourceManager.GetString("CommonDialogsForm_CommonDialogsForm_Node_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node 4.
        /// </summary>
        public static string CommonDialogsForm_CommonDialogsForm_Node_3 {
            get {
                return ResourceManager.GetString("CommonDialogsForm_CommonDialogsForm_Node_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node 0.
        /// </summary>
        public static string CommonDialogsForm_CommonDialogsForm_Node_4 {
            get {
                return ResourceManager.GetString("CommonDialogsForm_CommonDialogsForm_Node_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node 1.
        /// </summary>
        public static string CommonDialogsForm_CommonDialogsForm_Node_5 {
            get {
                return ResourceManager.GetString("CommonDialogsForm_CommonDialogsForm_Node_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a Menu.
        /// </summary>
        public static string GtkMainForm_GtkMainForm_a_Menu {
            get {
                return ResourceManager.GetString("GtkMainForm_GtkMainForm_a_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to b Menu.
        /// </summary>
        public static string GtkMainForm_GtkMainForm_b_Menu {
            get {
                return ResourceManager.GetString("GtkMainForm_GtkMainForm_b_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bb Menu.
        /// </summary>
        public static string GtkMainForm_GtkMainForm_bb_Menu {
            get {
                return ResourceManager.GetString("GtkMainForm_GtkMainForm_bb_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bb Menu 2.
        /// </summary>
        public static string GtkMainForm_GtkMainForm_bb_Menu_2 {
            get {
                return ResourceManager.GetString("GtkMainForm_GtkMainForm_bb_Menu_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c Menu.
        /// </summary>
        public static string GtkMainForm_GtkMainForm_c_Menu {
            get {
                return ResourceManager.GetString("GtkMainForm_GtkMainForm_c_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Style Interface.
        /// </summary>
        public static string GtkMainForm_GtkMainForm_Default_Style_Interface {
            get {
                return ResourceManager.GetString("GtkMainForm_GtkMainForm_Default_Style_Interface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dropdown List 1.
        /// </summary>
        public static string GtkMainForm_GtkMainForm_Dropdown_List_1 {
            get {
                return ResourceManager.GetString("GtkMainForm_GtkMainForm_Dropdown_List_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dropdown Menu.
        /// </summary>
        public static string GtkMainForm_GtkMainForm_Dropdown_Menu {
            get {
                return ResourceManager.GetString("GtkMainForm_GtkMainForm_Dropdown_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item 1.
        /// </summary>
        public static string GtkMainForm_GtkMainForm_Item_1 {
            get {
                return ResourceManager.GetString("GtkMainForm_GtkMainForm_Item_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item 2.
        /// </summary>
        public static string GtkMainForm_GtkMainForm_Item_2 {
            get {
                return ResourceManager.GetString("GtkMainForm_GtkMainForm_Item_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List View.
        /// </summary>
        public static string GtkMainForm_GtkMainForm_List_View {
            get {
                return ResourceManager.GetString("GtkMainForm_GtkMainForm_List_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu 1.
        /// </summary>
        public static string GtkMainForm_GtkMainForm_Menu_1 {
            get {
                return ResourceManager.GetString("GtkMainForm_GtkMainForm_Menu_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu 2.
        /// </summary>
        public static string GtkMainForm_GtkMainForm_Menu_2 {
            get {
                return ResourceManager.GetString("GtkMainForm_GtkMainForm_Menu_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Main Window.
        /// </summary>
        public static string GtkMainForm_GtkMainForm_Open_Main_Window {
            get {
                return ResourceManager.GetString("GtkMainForm_GtkMainForm_Open_Main_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string GtkMainForm_GtkMainForm_Print {
            get {
                return ResourceManager.GetString("GtkMainForm_GtkMainForm_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider Value.
        /// </summary>
        public static string GtkMainForm_GtkMainForm_Slider_Value {
            get {
                return ResourceManager.GetString("GtkMainForm_GtkMainForm_Slider_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split Container Layout.
        /// </summary>
        public static string GtkMainForm_GtkMainForm_Split_Container_Layout {
            get {
                return ResourceManager.GetString("GtkMainForm_GtkMainForm_Split_Container_Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Text.
        /// </summary>
        public static string GtkMainForm_GtkMainForm_Status_Text {
            get {
                return ResourceManager.GetString("GtkMainForm_GtkMainForm_Status_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a UserControl placeholder.
        /// </summary>
        public static string GtkMainForm_GtkMainForm_This_is_a_UserControl_placeholder {
            get {
                return ResourceManager.GetString("GtkMainForm_GtkMainForm_This_is_a_UserControl_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to testText.
        /// </summary>
        public static string GtkMainForm_panel3_Paint_testText {
            get {
                return ResourceManager.GetString("GtkMainForm_panel3_Paint_testText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap img10 {
            get {
                object obj = ResourceManager.GetObject("img10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap img11 {
            get {
                object obj = ResourceManager.GetObject("img11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special note:
        ///Images added to ImageList must be placed in the Resource directory under the program directory (specific directories (such as imageList1) can be further added under this directory)
        ///Otherwise, the image cannot be read. The name of the image can be found in the xxx.Designer.cs file, such as:
        ///imageList1.Images.SetKeyName(0, &quot;010.jpg&quot;);
        ///imageList1.Images.SetKeyName(1, &quot;timg2.jpg&quot;);.
        /// </summary>
        public static string label1Text {
            get {
                return ResourceManager.GetString("label1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add group and data simultaneously.
        /// </summary>
        public static string ListViewForm_button1_Click_1_Add_group_and_data_simultaneously {
            get {
                return ResourceManager.GetString("ListViewForm_button1_Click_1_Add_group_and_data_simultaneously", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add data to a specified group.
        /// </summary>
        public static string ListViewForm_button1_Click_2_Add_data_to_a_specified_group {
            get {
                return ResourceManager.GetString("ListViewForm_button1_Click_2_Add_data_to_a_specified_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a method to add multi-column data.
        /// </summary>
        public static string ListViewForm_button1_Click_3_This_is_a_method_to_add_multi_column_data {
            get {
                return ResourceManager.GetString("ListViewForm_button1_Click_3_This_is_a_method_to_add_multi_column_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub-column data 1.
        /// </summary>
        public static string ListViewForm_button1_Click_4_Sub_column_data_1 {
            get {
                return ResourceManager.GetString("ListViewForm_button1_Click_4_Sub_column_data_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub-column data 2.
        /// </summary>
        public static string ListViewForm_button1_Click_5_Sub_column_data_2 {
            get {
                return ResourceManager.GetString("ListViewForm_button1_Click_5_Sub_column_data_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub-column data 3 Sub-column data 3 Sub-column data 3.
        /// </summary>
        public static string ListViewForm_button1_Click_6_Sub_column_data_3_Sub_column_data_3_Sub_column_data_3 {
            get {
                return ResourceManager.GetString("ListViewForm_button1_Click_6_Sub_column_data_3_Sub_column_data_3_Sub_column_data_" +
                        "3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt; Monitoring Scroll Event Log.
        /// </summary>
        public static string ListViewForm_ListViewForm___Monitoring_Scroll_Event_Log {
            get {
                return ResourceManager.GetString("ListViewForm_ListViewForm___Monitoring_Scroll_Event_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0-Exception Warning 0 --- Server Room Air Conditioning Monitoring Event --- 638526419125153303 ------ 2024/5/30 4:58:32.
        /// </summary>
        public static string ListViewForm_ListViewForm__0_Exception_Warning_0_____Server_Room_Air_Conditioning_Monitoring_Event_____638526419125153303________2024_5_30_4_58_32 {
            get {
                return ResourceManager.GetString("ListViewForm_ListViewForm__0_Exception_Warning_0_____Server_Room_Air_Conditioning" +
                        "_Monitoring_Event_____638526419125153303________2024_5_30_4_58_32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1-Exception Warning 1 --- Server Room Air Conditioning Monitoring Event --- 638526419135198480 ------ 2024/5/30 4:58:33.
        /// </summary>
        public static string ListViewForm_ListViewForm__1_Exception_Warning_1_____Server_Room_Air_Conditioning_Monitoring_Event_____638526419135198480________2024_5_30_4_58_33 {
            get {
                return ResourceManager.GetString("ListViewForm_ListViewForm__1_Exception_Warning_1_____Server_Room_Air_Conditioning" +
                        "_Monitoring_Event_____638526419135198480________2024_5_30_4_58_33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2-Exception Warning 2 --- Server Room Air Conditioning Monitoring Event --- 638526419155233741 ------ 2024/5/30 4:58:35.
        /// </summary>
        public static string ListViewForm_ListViewForm__2_Exception_Warning_2_____Server_Room_Air_Conditioning_Monitoring_Event_____638526419155233741________2024_5_30_4_58_35 {
            get {
                return ResourceManager.GetString("ListViewForm_ListViewForm__2_Exception_Warning_2_____Server_Room_Air_Conditioning" +
                        "_Monitoring_Event_____638526419155233741________2024_5_30_4_58_35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3-Exception Warning 3 --- Server Room Air Conditioning Monitoring Event --- 638526419495254800 ------ 2024/5/30 4:59:09.
        /// </summary>
        public static string ListViewForm_ListViewForm__3_Exception_Warning_3_____Server_Room_Air_Conditioning_Monitoring_Event_____638526419495254800________2024_5_30_4_59_09 {
            get {
                return ResourceManager.GetString("ListViewForm_ListViewForm__3_Exception_Warning_3_____Server_Room_Air_Conditioning" +
                        "_Monitoring_Event_____638526419495254800________2024_5_30_4_59_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4-Exception Warning 4 --- Server Room Air Conditioning Monitoring Event --- 638526419505198651 ------ 2024/5/30 4:59:10.
        /// </summary>
        public static string ListViewForm_ListViewForm__4_Exception_Warning_4_____Server_Room_Air_Conditioning_Monitoring_Event_____638526419505198651________2024_5_30_4_59_10 {
            get {
                return ResourceManager.GetString("ListViewForm_ListViewForm__4_Exception_Warning_4_____Server_Room_Air_Conditioning" +
                        "_Monitoring_Event_____638526419505198651________2024_5_30_4_59_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 432321.
        /// </summary>
        public static string ListViewForm_ListViewForm__432321 {
            get {
                return ResourceManager.GetString("ListViewForm_ListViewForm__432321", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5-Exception Warning 5 --- Server Room Air Conditioning Monitoring Event --- 638526419565218661 ------ 2024/5/30 4:59:16.
        /// </summary>
        public static string ListViewForm_ListViewForm__5_Exception_Warning_5_____Server_Room_Air_Conditioning_Monitoring_Event_____638526419565218661________2024_5_30_4_59_16 {
            get {
                return ResourceManager.GetString("ListViewForm_ListViewForm__5_Exception_Warning_5_____Server_Room_Air_Conditioning" +
                        "_Monitoring_Event_____638526419565218661________2024_5_30_4_59_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ListView control provides the infrastructure to display a set of data items in different layouts or views. For example, a user may want to display data items in a table while allowing sorting of the table’s columns..
        /// </summary>
        public static string ListViewForm_ListViewForm_A {
            get {
                return ResourceManager.GetString("ListViewForm_ListViewForm_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bind Data to ListView.
        /// </summary>
        public static string ListViewForm_ListViewForm_Bind_Data_to_ListView {
            get {
                return ResourceManager.GetString("ListViewForm_ListViewForm_Bind_Data_to_ListView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group 1.
        /// </summary>
        public static string ListViewForm_ListViewForm_Group_1 {
            get {
                return ResourceManager.GetString("ListViewForm_ListViewForm_Group_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group 2fffffffffffffffffffffffffffffff.
        /// </summary>
        public static string ListViewForm_ListViewForm_Group_2fffffffffffffffffffffffffffffff {
            get {
                return ResourceManager.GetString("ListViewForm_ListViewForm_Group_2fffffffffffffffffffffffffffffff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group 3.
        /// </summary>
        public static string ListViewForm_ListViewForm_Group_3 {
            get {
                return ResourceManager.GetString("ListViewForm_ListViewForm_Group_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Footer Title.
        /// </summary>
        public static string ListViewForm_ListViewForm_Group_Footer_Title {
            get {
                return ResourceManager.GetString("ListViewForm_ListViewForm_Group_Footer_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Header Subtitle.
        /// </summary>
        public static string ListViewForm_ListViewForm_Group_Header_Subtitle {
            get {
                return ResourceManager.GetString("ListViewForm_ListViewForm_Group_Header_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group header title.
        /// </summary>
        public static string ListViewForm_ListViewForm_Group_Header_Title {
            get {
                return ResourceManager.GetString("ListViewForm_ListViewForm_Group_Header_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to group2.
        /// </summary>
        public static string ListViewForm_ListViewForm_group2 {
            get {
                return ResourceManager.GetString("ListViewForm_ListViewForm_group2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ListView Defines View Modes.
        /// </summary>
        public static string ListViewForm_ListViewForm_ListView_Defines_View_Modes {
            get {
                return ResourceManager.GetString("ListViewForm_ListViewForm_ListView_Defines_View_Modes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ListView Grouping.
        /// </summary>
        public static string ListViewForm_ListViewForm_ListView_Grouping {
            get {
                return ResourceManager.GetString("ListViewForm_ListViewForm_ListView_Grouping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ListView is derived from ListBox. Typically, the items of this control are members of a data collection and are represented as ListViewItem objects..
        /// </summary>
        public static string ListViewForm_ListViewForm_ListView_is_derived_from_ListBox__Typically__the_items_of_this_control_are_members_of_a_data_collection_and_are_represented_as_ListViewItem_objects_ {
            get {
                return ResourceManager.GetString("ListViewForm_ListViewForm_ListView_is_derived_from_ListBox__Typically__the_items_" +
                        "of_this_control_are_members_of_a_data_collection_and_are_represented_as_ListView" +
                        "Item_objects_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to listView1.Groups.Add().
        /// </summary>
        public static string ListViewForm_ListViewForm_listView1_Groups_Add__ {
            get {
                return ResourceManager.GetString("ListViewForm_ListViewForm_listView1_Groups_Add__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to listView1.Items.Add();.
        /// </summary>
        public static string ListViewForm_ListViewForm_listView1_Items_Add___ {
            get {
                return ResourceManager.GetString("ListViewForm_ListViewForm_listView1_Items_Add___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to listViewGroup1.
        /// </summary>
        public static string ListViewForm_ListViewForm_listViewGroup1 {
            get {
                return ResourceManager.GetString("ListViewForm_ListViewForm_listViewGroup1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ListViewGroup2.
        /// </summary>
        public static string ListViewForm_ListViewForm_ListViewGroup2 {
            get {
                return ResourceManager.GetString("ListViewForm_ListViewForm_ListViewGroup2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ListViewItem is a ContentControl and can only contain a single child element. However, this child element can be any visual element..
        /// </summary>
        public static string ListViewForm_ListViewForm_ListViewItem_is_a_ContentControl_and_can_only_contain_a_single_child_element__However__this_child_element_can_be_any_visual_element_ {
            get {
                return ResourceManager.GetString("ListViewForm_ListViewForm_ListViewItem_is_a_ContentControl_and_can_only_contain_a" +
                        "_single_child_element__However__this_child_element_can_be_any_visual_element_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.Details.
        /// </summary>
        public static string ListViewForm_ListViewForm_View_Details {
            get {
                return ResourceManager.GetString("ListViewForm_ListViewForm_View_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.LargeIcon.
        /// </summary>
        public static string ListViewForm_ListViewForm_View_LargeIcon {
            get {
                return ResourceManager.GetString("ListViewForm_ListViewForm_View_LargeIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.List.
        /// </summary>
        public static string ListViewForm_ListViewForm_View_List {
            get {
                return ResourceManager.GetString("ListViewForm_ListViewForm_View_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is ListView?.
        /// </summary>
        public static string ListViewForm_ListViewForm_What_is_ListView_ {
            get {
                return ResourceManager.GetString("ListViewForm_ListViewForm_What_is_ListView_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Warning {0} --- Server Room Air Conditioning Operation Monitoring Event --- {1} ------ {2}.
        /// </summary>
        public static string ListViewForm_Timer1_Tick_Exception_Warning__0______Server_Room_Air_Conditioning_Operation_Monitoring_Event______1__________2_ {
            get {
                return ResourceManager.GetString("ListViewForm_Timer1_Tick_Exception_Warning__0______Server_Room_Air_Conditioning_O" +
                        "peration_Monitoring_Event______1__________2_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beijing|Tianjin|Henan Province|Shanxi Province|Inner Mongolia Autonomous Region|Liaoning Province|Jilin Province|Heilongjiang Province|Shanghai|Jiangsu Province|Zhejiang Province|Anhui Province|Fujian Province.
        /// </summary>
        public static string Resources_TestDataForm_TestDataForm_Load_6 {
            get {
                return ResourceManager.GetString("Resources.TestDataForm_TestDataForm_Load_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Economic Zone.
        /// </summary>
        public static string Resources_TestDataForm_TestDataForm_Load_7 {
            get {
                return ResourceManager.GetString("Resources.TestDataForm_TestDataForm_Load_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy-MM-dd HH:mm:ss.
        /// </summary>
        public static string Resources_TestDataForm_TestDataForm_Load_8 {
            get {
                return ResourceManager.GetString("Resources.TestDataForm_TestDataForm_Load_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct-controlled Municipality.
        /// </summary>
        public static string Resources_TestDataForm_TestDataForm_Load_9 {
            get {
                return ResourceManager.GetString("Resources.TestDataForm_TestDataForm_Load_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationwide.
        /// </summary>
        public static string Resources_TestDataForm_TestDataForm_Load_B {
            get {
                return ResourceManager.GetString("Resources.TestDataForm_TestDataForm_Load_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0000-MM-dd HH:mm.
        /// </summary>
        public static string Resources_TestDataForm_TestDataForm_Load_C {
            get {
                return ResourceManager.GetString("Resources.TestDataForm_TestDataForm_Load_C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ListView Demo.
        /// </summary>
        public static string Resources_TestDataForm_TestDataForm_Load_D {
            get {
                return ResourceManager.GetString("Resources.TestDataForm_TestDataForm_Load_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Grid Example.
        /// </summary>
        public static string Resources_TestDataForm_TestDataForm_Load_E {
            get {
                return ResourceManager.GetString("Resources.TestDataForm_TestDataForm_Load_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container Table Example.
        /// </summary>
        public static string Resources_TestDataForm_TestDataForm_Load_F {
            get {
                return ResourceManager.GetString("Resources.TestDataForm_TestDataForm_Load_F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a RichTextBox, this is a RichTextBox, this is a RichTextBox, this is a RichTextBox, this is a RichTextBox, this is a RichTextBox, this is a RichTextBox, this is a RichTextBox, this is a RichTextBox, this is a RichTextBox, this is a RichTextBox, this is a RichTextBox, this is a RichTextBox.
        /// </summary>
        public static string Resources_TestDataForm_TestDataForm_Load_G {
            get {
                return ResourceManager.GetString("Resources.TestDataForm_TestDataForm_Load_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawing and Image Example.
        /// </summary>
        public static string Resources_TestDataForm_TestDataForm_Load_H {
            get {
                return ResourceManager.GetString("Resources.TestDataForm_TestDataForm_Load_H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu One.
        /// </summary>
        public static string Resources_TestDataForm_TestDataForm_Load_I {
            get {
                return ResourceManager.GetString("Resources.TestDataForm_TestDataForm_Load_I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Two.
        /// </summary>
        public static string Resources_TestDataForm_TestDataForm_Load_J {
            get {
                return ResourceManager.GetString("Resources.TestDataForm_TestDataForm_Load_J", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Three.
        /// </summary>
        public static string Resources_TestDataForm_TestDataForm_Load_K {
            get {
                return ResourceManager.GetString("Resources.TestDataForm_TestDataForm_Load_K", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Menu 1.
        /// </summary>
        public static string Resources_TestDataForm_TestDataForm_Load_L {
            get {
                return ResourceManager.GetString("Resources.TestDataForm_TestDataForm_Load_L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary Menu 1.
        /// </summary>
        public static string Resources_TestDataForm_TestDataForm_Load_M {
            get {
                return ResourceManager.GetString("Resources.TestDataForm_TestDataForm_Load_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tertiary Menu 1.
        /// </summary>
        public static string Resources_TestDataForm_TestDataForm_Load_N {
            get {
                return ResourceManager.GetString("Resources.TestDataForm_TestDataForm_Load_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary Menu 2.
        /// </summary>
        public static string Resources_TestDataForm_TestDataForm_Load_O {
            get {
                return ResourceManager.GetString("Resources.TestDataForm_TestDataForm_Load_O", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Menu 2.
        /// </summary>
        public static string Resources_TestDataForm_TestDataForm_Load_P {
            get {
                return ResourceManager.GetString("Resources.TestDataForm_TestDataForm_Load_P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Resources_TestDataForm_TestDataForm_Load_Q {
            get {
                return ResourceManager.GetString("Resources.TestDataForm_TestDataForm_Load_Q", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Resources_TestDataForm_TestDataForm_Load_R {
            get {
                return ResourceManager.GetString("Resources.TestDataForm_TestDataForm_Load_R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date &amp; Time.
        /// </summary>
        public static string Resources_TestDataForm_TestDataForm_Load_S {
            get {
                return ResourceManager.GetString("Resources.TestDataForm_TestDataForm_Load_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Resources_TestDataForm_TestDataForm_Load_T {
            get {
                return ResourceManager.GetString("Resources.TestDataForm_TestDataForm_Load_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Resources_TestDataForm_TestDataForm_Load_U {
            get {
                return ResourceManager.GetString("Resources.TestDataForm_TestDataForm_Load_U", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Number.
        /// </summary>
        public static string Resources_TestDataForm_TestDataForm_Load_V {
            get {
                return ResourceManager.GetString("Resources.TestDataForm_TestDataForm_Load_V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestData1.en.json.
        /// </summary>
        public static string testdata1Json {
            get {
                return ResourceManager.GetString("testdata1Json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Load data point yes  
        ///2. Do not load data point no.
        /// </summary>
        public static string TestDataForm_button1_1 {
            get {
                return ResourceManager.GetString("TestDataForm_button1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Data Prompt.
        /// </summary>
        public static string TestDataForm_button1_2 {
            get {
                return ResourceManager.GetString("TestDataForm_button1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load data point yes, load data  
        ///Point yes, load data point yes, load data point yes.
        /// </summary>
        public static string TestDataForm_button1_3 {
            get {
                return ResourceManager.GetString("TestDataForm_button1_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string TestDataForm_button1_4 {
            get {
                return ResourceManager.GetString("TestDataForm_button1_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asynchronous Network Image Loading.
        /// </summary>
        public static string TestDataForm_button1_5 {
            get {
                return ResourceManager.GetString("TestDataForm_button1_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asynchronous loading of network images.
        /// </summary>
        public static string TestDataForm_button1_Click_Asynchronous_loading_of_network_images {
            get {
                return ResourceManager.GetString("TestDataForm_button1_Click_Asynchronous_loading_of_network_images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestData1.en.json.
        /// </summary>
        public static string TestDataForm_Form1_Load_TestData1_json {
            get {
                return ResourceManager.GetString("TestDataForm_Form1_Load_TestData1_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the Paint Graphics sample effect.
        /// </summary>
        public static string TestDataForm_pictureBox2_Paint_This_is_the_Paint_Graphics_sample_effect {
            get {
                return ResourceManager.GetString("TestDataForm_pictureBox2_Paint_This_is_the_Paint_Graphics_sample_effect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Data Table Data.
        /// </summary>
        public static string TestDataForm_TestDataForm_Load_1 {
            get {
                return ResourceManager.GetString("TestDataForm_TestDataForm_Load_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a dropdown list control data test.
        /// </summary>
        public static string TestDataForm_TestDataForm_Load_2 {
            get {
                return ResourceManager.GetString("TestDataForm_TestDataForm_Load_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Color.
        /// </summary>
        public static string TestDataForm_TestDataForm_Load_2B {
            get {
                return ResourceManager.GetString("TestDataForm_TestDataForm_Load_2B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Box Title.
        /// </summary>
        public static string TestDataForm_TestDataForm_Load_3 {
            get {
                return ResourceManager.GetString("TestDataForm_TestDataForm_Load_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string TestDataForm_TestDataForm_Load_4 {
            get {
                return ResourceManager.GetString("TestDataForm_TestDataForm_Load_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Color Button.
        /// </summary>
        public static string TestDataForm_TestDataForm_Load_5 {
            get {
                return ResourceManager.GetString("TestDataForm_TestDataForm_Load_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Website:.
        /// </summary>
        public static string TestDataForm_TestDataForm_Open_Website_A {
            get {
                return ResourceManager.GetString("TestDataForm_TestDataForm_Open_Website_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap timg {
            get {
                object obj = ResourceManager.GetObject("timg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap timg6 {
            get {
                object obj = ResourceManager.GetObject("timg6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.SmallIcon.
        /// </summary>
        public static string ViewSmallIcon {
            get {
                return ResourceManager.GetString("ViewSmallIcon", resourceCulture);
            }
        }
    }
}
